spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/midb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: update